name: cloud_frog
description: A library to help build secure Google Cloud services using Dart Frog.
version: 1.1.0
repository: https://github.com/labrom/cloud_frog

environment:
  sdk: ^3.5.0

dependencies:
  asn1lib: ^1.5.3
  dart_frog: ^1.1.0
  dart_frog_auth: ^1.1.0
  dart_frog_request_logger: ^0.0.2
  dart_jsonwebtoken: ^2.14.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

dev_dependencies:
  build_runner: ^2.4.12
  lints: ^4.0.0
  test: ^1.25.8
  very_good_analysis: ^6.0.0

